---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    app: hello-world

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deploy
  namespace: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world-server:minikube
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: hello-world
  labels:
    app: hello-world
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: hello-world

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: hello-world
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: world.helloclue.com
   http:
     paths:
     - path: /
       backend:
         serviceName: hello-world-svc
         servicePort: 8080
