---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: clue
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: world.helloclue.com
      http:
      # TODO: https://world.helloclue.com/ -> http://container:8080/
